### ISSUE TITLE
Antivirus block

### ISSUE THREAD

**Issue by LotosikRa** [YurkoFlisk/checkers#3]
My AvastAntivirus has blocked your release file `checkers_static_1.5.exe` and send it to AvastAnivirus' lab for additional check.

Whow can you comment this event?

**Comment by YurkoFlisk** [comment]
This can be a false-positive alert. I think it is related to VS 2015 compiler optimizations(i turned all them on). Here's report on Virustotal for [checkers_1.5](https://www.virustotal.com/uk/file/e0c79ceac91b0669257d0098f481e2ac7e91bba0291fd73ef920d646840d622d/analysis/1472822595/) and for [checkers_static_1.5.exe](https://www.virustotal.com/uk/file/c5102d458a5f82bfdbae8dc93e19ef0c20ecba5ceee49cd025ad0ad47bfa34a6/analysis/1472820703/)
